In [1]:
!pip install numpy

In [3]:
import numpy as np

In [15]:
a=np.array([1,2,3])
b=np.array([(1.5,2,3), (4,5,6)], dtype = float)
c=np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [17]:
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [25]:
np.ones((5))#rows

array([1., 1., 1., 1., 1.])

In [19]:
np.zeros((3,4))#rows,cols

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((2,3,4))#shapes , rows, cols

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
d=np.arange(10,25,3)
print(d)

[10 13 16 19 22]


In [31]:
np.linspace(0,8,7)

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [33]:
e=np.full((6),9)
print(e)
print(e.ndim)

[9 9 9 9 9 9]
1


In [35]:
e=np.full((2,2),9)
print(e)
print(e.ndim)

[[9 9]
 [9 9]]
2


In [41]:
e=np.full((2,2,2),9)
print(e)
print("no of demension: ",e.ndim)

[[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]
no of demension:  3


In [43]:
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
np.random.random((2,3))

array([[0.80778842, 0.56224877, 0.97570288],
       [0.91294249, 0.41052543, 0.01737049]])

In [60]:
np.random.randint(1,10)

1

In [64]:
arr=np.array([[1,2,3,4],
              [5,6,7,8,],
              [9,10,11,12]])
print(arr.shape)

(3, 4)


In [66]:
arr=np.array([[1,2,3,4],
              [5,6,7,8,],
              [9,10,11,12]])
print(arr.size)

12


In [ ]:
arr=np.array([[1,2,3,4],
              [5,6,7,8,],
              [9,10,11,12]])